### ISSUE TITLE
theme error while building app

### ISSUE THREAD

**Issue by Amit-wct** [payu-intrepos/PayUCustomBrowser-Flutter#1]
D/libMEOW (14290): meow new tls: 0xb400006fd2082780
D/libMEOW (14290): applied 0 plugin for [com.example.tsim_app].
D/libMEOW (14290): meow delete tls: 0xb400006fd2082780
D/IS_CTS_MODE(14290): false
D/MULTI_WINDOW_ENABLED(14290): false
D/DecorView[](14290): getWindowModeFromSystem  windowmode is 1
W/IconCustomizer(14290): getCustomizedIconW 122
D/AndroidRuntime(14290): Shutting down VM
E/AndroidRuntime(14290): FATAL EXCEPTION: main
E/AndroidRuntime(14290): Process: com.example.tsim_app, PID: 14290
E/AndroidRuntime(14290): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.tsim_app/com.payu.custombrowser.CBActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(14290): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3896)
E/AndroidRuntime(14290): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4042)
E/AndroidRuntime(14290): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
E/AndroidRuntime(14290): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14290): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14290): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2436)
E/AndroidRuntime(14290): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14290): 	at android.os.Looper.loopOnce(Looper.java:211)
E/AndroidRuntime(14290): 	at android.os.Looper.loop(Looper.java:300)
E/AndroidRuntime(14290): 	at android.app.ActivityThread.main(ActivityThread.java:8324)
E/AndroidRuntime(14290): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14290): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
E/AndroidRuntime(14290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
E/AndroidRuntime(14290): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(14290): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:852)
E/AndroidRuntime(14290): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:815)
E/AndroidRuntime(14290): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:703)
E/AndroidRuntime(14290): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
E/AndroidRuntime(14290): 	at com.payu.custombrowser.CBActivity.onCreate(SourceFile:2)
E/AndroidRuntime(14290): 	at android.app.Activity.performCreate(Activity.java:8547)
E/AndroidRuntime(14290): 	at android.app.Activity.performCreate(Activity.java:8511)
E/AndroidRuntime(14290): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
E/AndroidRuntime(14290): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3877)
E/AndroidRuntime(14290): 	... 12 more
W/xample.tsim_app(14290): type=1400 audit(0.0:184551): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184552): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184553): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184554): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184555): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/OOMEventManagerFK(14290): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/xample.tsim_app(14290): type=1400 audit(0.0:184556): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184557): avc: denied { getattr } for path="/data/miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
W/xample.tsim_app(14290): type=1400 audit(0.0:184558): avc: denied { search } for name="miuilog" dev="dm-50" ino=526 scontext=u:r:untrusted_app:s0:c94,c257,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.example.tsim_app
I/Process (14290): Process is going to kill itself!
I/Process (14290): java.lang.Exception
I/Process (14290): 	at android.os.Process.killProcess(Process.java:1330)
I/Process (14290): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:203)
I/Process (14290): 	at com.payu.crashlogger.b.a(SourceFile:24)
I/Process (14290): 	at com.payu.crashlogger.b$$ExternalSyntheticLambda0.uncaughtException(Unknown Source:2)
I/Process (14290): 	at com.payu.payuanalytics.analytics.manager.AnalyticsDataManager._init_$lambda-3(AnalyticsDataManager.kt:358)
I/Process (14290): 	at com.payu.payuanalytics.analytics.manager.AnalyticsDataManager.$r8$lambda$ITpyDMeS827l5PeYDfiJkJDEkb0(Unknown Source:0)
I/Process (14290): 	at com.payu.payuanalytics.analytics.manager.AnalyticsDataManager$$ExternalSyntheticLambda1.uncaughtException(Unknown Source:4)
I/Process (14290): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process (14290): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process (14290): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process (14290): Sending signal. PID: 14290 SIG: 9
Lost connection to device.

**Comment by shahfaizalc** [comment]
@Amit-wct  kindly use 0.0.3 version. The issue has been resolved
